fix: telegraf response_timeout to timeout
Azure/secrets-store-csi-driver-provider-azure pull request #1616
Opened 2024-07-18 16:26 UTC by haodeon

**Reason for Change**:

Telegraf sidecar in `akvsecretsprovider-arc-monitoring` pod is crashing upon startup because `telegraf.conf` uses deprecated option `response_timeout`.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [x] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

2024-07-18 19:30 UTC, nilekhc approved these changes

2024-07-18 20:48 UTC, aramase requested changes
Please update the yamls in the [manifest_staging/](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/manifest_staging/) folder and revert any changes in `charts/`. 

`manifest_staging` folder is where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder with the next release.

2024-07-19 19:19 UTC, nilekhc commented
/azp run pr-e2e-azure

2024-07-22 17:36 UTC, nilekhc commented
/azp run pr-e2e

2024-07-22 17:57 UTC, nilekhc approved these changes

2024-07-22 22:58 UTC, aramase approved these changes

2024-07-22 22:58 UTC, merged