Update provider-azure-installer.yaml to support OpenShift / ARO SCC
Azure/secrets-store-csi-driver-provider-azure pull request #364
Opened 2021-01-11 11:42 UTC by ezYakaEagle442

…with privileged: true

For OpenShift SCC requires privileged: true and also 2 settings below :
 for the CSI Driver : oc adm policy add-scc-to-user privileged system:serviceaccount:$target_namespace:secrets-store-csi-driver
 for the Azure KV Provider : oc adm policy add-scc-to-user privileged system:serviceaccount:$target_namespace:csi-secrets-store-provider-azure

**Reason for Change**:

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [ ] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

2021-01-11 12:00 UTC, ezYakaEagle442 commented
the [HELM Chart](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml) was correctly running with privileged: true

2021-01-11 17:15 UTC, aramase requested changes
@ezYakaEagle442 As mentioned in the PR template: 

```
<!--
**Is this a chart or deployment yaml update?**
If yes, please update the yamls in the [manifest_staging/](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/manifest_staging/) folder, where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder with the next release. Please also add the new configurable values to the configuration [table](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/manifest_staging/charts/csi-secrets-store-provider-azure#configuration). 
-->
```

Could you make these changes in the `manifest_staging/charts` dir instead? 

Also, this change would be required for the deployment manifests and helm charts in the `manifest_staging` dir.

2021-01-11 17:22 UTC, aramase commented
I've also opened an issue to track the documentation for this: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/365

2021-02-02 18:24 UTC, aramase approved these changes

2021-02-02 18:28 UTC, merged